export const apiUrls = {
  fetchContractPriceProfileInfoURL : 'rest/customer/fetchContractPriceProfileInfo',
  fetchAuthorizationDetailsURL : 'rest/authorization/fetchAuthorizationDetails',
  distributionCenterURL : 'rest/distributionCenter/distributionCentersForCompany',
  distributionCenterSaveURL : 'rest/distributionCenter/saveDistributionCenters',
  distributionCentersFetchURL : 'rest/distributionCenter/fetchSavedDistributionCenters',
  fetchPricingInformationURL : 'rest/contractPricing/fetchPricingInformation',
  savePricingInformationURL : 'rest/contractPricing/savePricingInformation',
  fetchMarkupGridURL : 'rest/markup/fetchMarkups',
  createDefaultItemLevelMarkupURL : 'rest/markup/createDefaultItemLevelMarkup',
  createDefaultSubgroupMarkupURL : 'rest/markup/createDefaultSubgroupMarkup',
  saveMarkupGridURL : 'rest/markup/saveMarkup',
  addExceptionURL : 'rest/markup/addException',
  renameMarkupExceptionURL : 'rest/markup/renameMarkupException',
  deleteMarkupExceptionURL : 'rest/markup/deleteMarkupException',
  saveMarkupIndicatorsURL : 'rest/markup/saveMarkupIndicators',
  fetchMarkupIndicatorsURL : 'rest/markup/fetchMarkupIndicators',
  fetchSplitcaseFeeURL : 'rest/splitcase/fetchSplitCase',
  splitCaseSaveURL : 'rest/splitcase/saveSplitCaseFee',
  fetchReviewDataURL : 'rest/review/fetchReviewData',
  createExhibitDocURL: 'rest/review/createExhibitDocument',
  fetchMarkupsAssignmentURL: 'rest/assignments/fetchMarkup',
  fetchCustomerTypes: 'rest/assignments/fetchCustomerTypes',
  findCustomer: 'rest/assignments/findCustomer',
  deleteItemLevelMarkupURL : 'rest/markup/deleteItemLevelMarkup',
  saveAssignmentsURL: 'rest/assignments/saveAssignments',
  fetchAllFutureItemsURL : 'rest/assignments/fetchAllFutureItems',
  saveItemAssignmentsURL: 'rest/assignments/assignItems',
  deleteRealCustomer: 'rest/assignments/deleteCustomerAssignment',
  savePricingExhibitURL: 'rest/review/savePricingExhibit',
  fetchClmUrl: 'rest/clm/returnToClm',
  activatePricingURL: 'rest/activatePricing/activatePricingForCustomer',
  deleteItemAssignmentURL: 'rest/assignments/deleteItemAssignment',
  deletePricingExhibitURL : 'rest/contractPricing/deletePricingExhibit',
  findItemInformationURL: 'rest/item/findItemInformation',
  findSubgroupInformationURL: 'rest/markup/findItemSubgroupInformation',
  deleteSubgroupMarkupURL : 'rest/markup/deleteSubgroupMarkup',
  enableActivatePricingURL: 'rest/activatePricing/enableActivatePricing',
  validateHasInProgressFurtheranceURL: 'rest/furtherance/hasInProgressFurtherance',
  deleteItemLevelMarkupFurtheranceURL: 'rest/furtherance/deleteItemLevelMarkup',
  fetchFurtheranceInfoURL: 'rest/furtherance/fetchFurtheranceInformation',
  saveFurtheranceInformationURL: 'rest/furtherance/saveFurtheranceInformation',
  createNewFurtheranceURL: 'rest/furtherance/createNewFurtherance',
  fetchInProgressFurtheranceInfoURL: 'rest/furtherance/fetchInProgressFurtheranceInfo',
  saveFurtheranceMarkupGridURL: 'rest/furtherance/saveMarkupForFurtherance',
  fetchMappedItemsForFurtheranceURL: 'rest/furtherance/fetchMappedItemsForFurtherance',
  activatePricingForFurtheranceURL: 'rest/furtherance/activatePricingForFurtherance',
  saveFurtheranceSplitCaseURL: 'rest/furtherance/saveSplitCaseFee',
  createFurtheranceDocumentURL: 'rest/furtherance/createFurtheranceDocument',
  enableActivatePricingForFurtheranceURL: 'rest/furtherance/enableActivatePricingForFurtherance',
  savePricingDocumentForFurtheranceURL: 'rest/furtherance/savePricingDocumentForFurtherance',
  saveMappedItemsForFurtheranceURL: 'rest/furtherance/assignItemsForFurtherance',
  deleteMappedItemForFurtheranceURL: 'rest/furtherance/deleteMappedItemForFurtherance',
  fetchCostGridURL: 'rest/costModel/fetchCostGrid',
  fetchCostModelListURL: 'rest/costModel/fetchAllActiveCostModels',
  saveCostModelGridURL: 'rest/costModel/saveCostGrid',
  canEditFurtherance: 'rest/authorization/canEditFurtherance',
  searchContractByContractNameURL: 'rest/search/searchContractsByContractName',
  searchContractByCustomerURL: 'rest/search/searchContractsByCustomer',
  searchContractByCppIdURL: 'rest/search/searchContractsByCPPId',
  checkForViewOnlyUserURL: 'rest/authorization/isUserAuthorizedToViewOnly'
};
