package com.gfs.cpp.common.exception;

public enum CPPExceptionType {

    // @formatter:off
    NOT_FOUND(100),
    DB_INSERTION_FAILED(101),
    DB_FETCH_FAILED(102),
    SERVICE_FAILED(103),
    SAVE_EXHIBIT_SERVICE_FAILED(104),
    NOT_VALID_STATUS(106),
    NO_CONTRACT_FOUND(107),
    HAS_REAL_CUSTOMER_MAPPING(108),
    INVALID_CONTRACT(109),
    CUSTOMER_NOT_FOUND(111),
    CUSTOMER_ALREADY_MAPPED_TO_ACTIVE_CONTRACT(112),
    HAS_MULTIPLE_CUSTOMER_MAPPING(113),
    CUSTOMER_ALREADY_MAPPED_TO_CONCEPTS(114),
    IN_PROGREESS_VERSION_FOUND(115),
    NOT_A_MEMBER_OF_DEFAULT_CUSTOMER(116),
    INVALID_CUSTOMER_FOUND(117),
    CREATE_CMG_CUSTOMER_FAILED(118),
    INACTIVE_CUSTOMER_FOUND(119),
    ITEM_ALREADY_EXIST(150),
    ACCESS_DENIED(120),
    NO_CUSTOMER_MAPPED_TO_DEFAULT_CONCEPT(121),
    CUSTOMER_MAPPED_TO_DEFAULT_IS_UNIT_TYPE(122),
    CLM_STATUS_NOT_DRAFT(130),
    EXPIRED_CONTRACT(131),
    SUBGROUP_ALREADY_EXIST(123),
    INVALID_SUBGROUP(124),
    NEW_CONTRACT_INVALID_STATUS(140),
    CANNOT_CREATE_FURTHERANCE(125),
    IN_PROGRESS_FURTHERANCE_FOUND(126),
    INVALID_AMENDMENT_EFFECTIVE_DATE(127),
    INVALID_FURTHERANCE_STATUS(128),
	FUTURE_ITEM_ADDED_IN_FURTHERANCE(129);
    
    // @formatter:on

    private Integer errorCode;

    CPPExceptionType(final Integer errorCode) {
        this.errorCode = errorCode;
    }

    public Integer getErrorCode() {
        return errorCode;
    }
}
