CREATE SEQUENCE PRICE_ADMIN.CPP_FURTHERANCE_SEQ MINVALUE 1 MAXVALUE 999999999 INCREMENT by 1 CACHE 20;

CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE (
	CPP_FURTHERANCE_SEQ			NUMBER(9) NOT NULL,
	CONTRACT_PRICE_PROFILE_SEQ 	NUMBER(9) NOT NULL,
	PRICE_ACTIVATED_TMSTMP		TIMESTAMP(6) WITH TIME ZONE,
	FURTHERANCE_STATUS_CODE		NUMBER (1) NOT NULL,
	PARENT_CLM_AGREEMENT_ID		VARCHAR2(100),
	FURTHERANCE_EFFECTIVE_DATE	DATE NOT NULL,
	CHANGE_REASON_TXT			VARCHAR2(200),
	CONTRACT_REFERENCE_TXT		VARCHAR2(1500),
	FURTHERANCE_DOCUMENT_GUID   VARCHAR2(100),
	CREATE_USER_ID				VARCHAR2(100) NOT NULL,
	CREATE_TMSTMP				TIMESTAMP(6) WITH TIME ZONE default systimestamp NOT NULL,
	LAST_UPDATE_USER_ID			VARCHAR2(100) NOT NULL,
	LAST_UPDATE_TMSTMP			TIMESTAMP(6) WITH TIME ZONE default systimestamp NOT NULL,
    CONSTRAINT CPP_FURTHERANCE_PK primary key (CPP_FURTHERANCE_SEQ),
	CONSTRAINT FK_CPP_FURTHERANCE_STATUS_01 foreign key(FURTHERANCE_STATUS_CODE)
		references PRICE_ADMIN.CPP_FURTHERANCE_STATUS(FURTHERANCE_STATUS_CODE),
	CONSTRAINT FK_CONTRACT_PRICE_ROFILE_01 foreign key(CONTRACT_PRICE_PROFILE_SEQ)
		references PRICE_ADMIN.CONTRACT_PRICE_ROFILE(CONTRACT_PRICE_PROFILE_SEQ),
	CONSTRAINT CPP_FURTHERANCE_UK1 UNIQUE (CONTRACT_PRICE_PROFILE_SEQ,PRICE_ACTIVATED_TMSTMP)	
);

