CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE_STATUS (
	FURTHERANCE_STATUS_CODE  NUMBER(1) NOT NULL,
	CODE_TABLE_REF_ID      	 NUMBER(9) NOT NULL,
	LAST_UPDATE_TMSTMP  	 timestamp(6) with time zone default systimestamp NOT NULL,
	LAST_UPDATE_USER_ID 	 VARCHAR2(100) NOT NULL,
	constraint CPP_FURTHERANCE_STATUS_PK primary key (FURTHERANCE_STATUS_CODE)
);
