CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE_ACTION (
	FURTHERANCE_ACTION_CODE  NUMBER(1) NOT NULL,
	CODE_TABLE_REF_ID      	 NUMBER(9) NOT NULL,
	LAST_UPDATE_TMSTMP  	 timestamp(6) with time zone default systimestamp NOT NULL,
	LAST_UPDATE_USER_ID 	 VARCHAR2(100) NOT NULL,
	constraint CPP_FURTHERANCE_ACTION_PK primary key (FURTHERANCE_ACTION_CODE)
);