INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_STATUS(FURTHERANCE_STATUS_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (1,38,SYSDATE,'v2aag');

INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_STATUS(FURTHERANCE_STATUS_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (2,38,SYSDATE,'v2aag');

INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_STATUS(FURTHERANCE_STATUS_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (3,38,SYSDATE,'v2aag');

INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_ACTION (FURTHERANCE_ACTION_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (1,39,SYSDATE, 'v2aag');

INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_ACTION (FURTHERANCE_ACTION_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (2,39,SYSDATE, 'v2aag');

INSERT INTO PRICE_ADMIN.CPP_FURTHERANCE_ACTION (FURTHERANCE_ACTION_CODE,CODE_TABLE_REF_ID,LAST_UPDATE_TMSTMP, LAST_UPDATE_USER_ID)
VALUES (3,39,SYSDATE, 'v2aag');

commit;