INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (38,'1', 'en', 'CPP_FURTHERANCE_STATUS', 'FURTHERANCE INITIATED','FI' );
INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (38,'2', 'en', 'CPP_FURTHERANCE_STATUS', 'FURTHERANCE SAVED','FS' );
INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (38, '3', 'en', 'CPP_FURTHERANCE_STATUS', 'PRICING ACTIVATED', 'PRICE ACTIVE');

commit;