INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (39,'1', 'en', 'CPP_FURTHERANCE_ACTION', 'ADDED', 'ADDED');
INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (39, '2', 'en', 'CPP_FURTHERANCE_ACTION', 'UPDATED', 'UPDATED');
INSERT INTO PRICE_ADMIN.PRICE_CODES_LANGUAGE_DESC (CODE_TABLE_REF_ID, CODE_VALUE, LANGUAGE_TYPE_CODE, CODE_TABLE_NAME, CODE_DESC, DISPLAY_SHORT_DESC) VALUES (39, '3', 'en', 'CPP_FURTHERANCE_ACTION', 'DELETED', 'DELETED');

commit;